%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 800
distortion_parameters:
   k1: -0.161282
   k2: 0.093215
   p1: -0.001904
   p2: 0.000379
projection_parameters:
   fx: 1655.018311
   fy: 1679.957397
   cx: 665.797738
   cy: 378.563818
